### ISSUE TITLE
[TECH DEBT] Need to go through Salt Project issues and PRs

### ISSUE THREAD

**Issue by nicholasmhughes** [salt-extensions/saltext-proxmox#5]
Each issue should validated. If still valid, port the issue over to this repo (copy/paste of main content is fine). Once the issue is recorded in this repo, close the original issue in Salt Project with a link to the new issue for folks who are tracking it. If the issue is not valid, close the issue in Salt Project with a note as to why.

- [x] https://github.com/saltstack/salt/issues/56527
- [x] https://github.com/saltstack/salt/issues/56633
- [x] https://github.com/saltstack/salt/issues/59057
- [x] https://github.com/saltstack/salt/issues/59528
- [x] https://github.com/saltstack/salt/issues/60947
- [x] https://github.com/saltstack/salt/issues/61136
- [x] https://github.com/saltstack/salt/issues/61215
- [x] https://github.com/saltstack/salt/issues/62945
- [x] https://github.com/saltstack/salt/issues/62947

The following PRs should be checked for validity. If valid, the changes can either be ported over to a PR in this repo or a comment can be left with the original contributor to move the PR over to this repo. If the latter is chosen, follow-up will be required to ensure the change is recorded here. Once moved to this repo, the PR in the Salt Project repo should be closed without merge.

- [x] https://github.com/saltstack/salt/pull/55246
- [ ] https://github.com/saltstack/salt/pull/58843
- [ ] https://github.com/saltstack/salt/pull/59343

**Comment by mthibaut** [comment]
Please add https://github.com/saltstack/salt/issues/61136 to the list as documentation tech debt.

**Comment by mthibaut** [comment]
Added issue https://github.com/salt-extensions/saltext-proxmox/issues/8 replacing https://github.com/saltstack/salt/issues/56633

**Comment by mthibaut** [comment]
Tech debt replacement list:

- https://github.com/saltstack/salt/issues/62945 with https://github.com/salt-extensions/saltext-proxmox/pull/6
- https://github.com/saltstack/salt/issues/61136 with https://github.com/salt-extensions/saltext-proxmox/issues/9
